### ISSUE TITLE
Error by adding the repo: is not a valid add-on repository

### ISSUE THREAD

**Issue by marius17si** [fsaris/home-assistant-awox#103]
When I try to add the repo I get the following error:

https://github.com/fsaris/home-assistant-awox is not a valid add-on repository

Steps to reproduce:

1. Go to settings
2. Add-Ons
3. Add-On Store
4. In the upper right croner the three points
5. Repositorys
6. Add the link https://github.com/fsaris/home-assistant-awox

**Comment by fsaris** [comment]
This is no addon. But a custom component see https://github.com/fsaris/home-assistant-awox#install-with-hacs-recommended
