### ISSUE TITLE
Adding EGLO/AwoX Connect-C Sensor

### ISSUE THREAD

**Issue by AMDFreak2006** [fsaris/home-assistant-awox#104]
Currently the library only supports lights but no sensors.

From Eglo there is (since many years) the Connect-C sensor [click here](https://www.eglo.com/de/zubehoer-connect-sensor-97475.html) which combines a motion detection sensor with a brightness sensors (like most motion detection sensors...) and the Eglo/Awox BLE-interface. I have it in use since many years and it works quite flawlessly. However the possible things one can do with it in the original Awox app are sadly very limited.

Would it be possible to add it to the library?

Which information are needed for integration? I will of course try to provide everything which is needed.

HAOS 11.1 with HA core 2023.11.2
home-assistant-awox release 0.1.5

**Comment by fsaris** [comment]
Closed for now, if we can get this working for https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/discussions/39 and #110 is resolved this could be picked up here.
