### ISSUE TITLE
Update of light status (switching between RGB and TW mode) needs 30-60 seconds and changing brightness shortly after RGB/TW mode change is not correctly done

### ISSUE THREAD

**Issue by AMDFreak2006** [fsaris/home-assistant-awox#105]
It seems as if the integration only polls the state of the lights only every 30 or 60 seconds if a light has been switched from RGB color mode to a TW mode.

If only selection a new RGB color, when the light is already on RGB mode, the color is presented in the Home Assisant GUI immediately. However if one clicks on a TW white-color, the lamp immediately reacts, but the HA interface still shows the selected RGB color from before.
Even more important:
Additionally if one tries to change the brightness of RGB or TW directly after switching the mode (and not waiting 30-60 seconds for HA to update the status in the GUI) the light switches back to the prior mode and applies the brightness change on this prior mode instead of the color/tw selected seconds before.

A workaround (especially in automations) is to first set the target brightness and afterwards change to the desired RGB color or TW. Doing it in the opposite order, results in the bug described above. Due to the bug it's also not possible to directly set brightness and target color/mode in the same step within an automation GUI-based script (no source-code).

So for example it currently is not possible to switch from RGB red color with 80% brightness to a TW white color with 30% brightness in one step and even if divided in to steps a specific order has to be used, which is not necessary when using the original Awox app or the physical BLE remote.
A sure sign that this "fallback to the old color"-bug wont happen is to wait 30-60 seconds until the GUI shows the newly selected mode(RGB or TW) in the dashboard.

HAOS 11.1 with HA core 2023.11.2
home-assistant-awox release 0.1.5

**Comment by fsaris** [comment]
See https://github.com/fsaris/home-assistant-awox/discussions/111#discussioncomment-7611114 for the delay issues.

The update cycle had been improved in https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub and could be ported back here once #110 is resolved.
