### ISSUE TITLE
Update of light status when changed by external sources needs 30-60 seconds

### ISSUE THREAD

**Issue by AMDFreak2006** [fsaris/home-assistant-awox#107]
When the status of the light (color, brightness, mode, status) ist changed externally by Awox App or original phyisical BLE remote, the status in the HA GUI only changes after 30-60 seconds.

Is the polling intervall changeable or is there a better way to get a status update quicker?

HAOS 11.1 with HA core 2023.11.2
home-assistant-awox release 0.1.5

**Comment by fsaris** [comment]
The update cycle has been improved in https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub and could be ported back here once https://github.com/fsaris/home-assistant-awox/issues/110 is resolved.
