### ISSUE TITLE
Wifi Light compatibility

### ISSUE THREAD

**Issue by joffrey71** [fsaris/home-assistant-awox#17]
Hello,

I'm trying to use this plugin to control my Awox striimlight (Wifi).
I don't know if this plugin is compatible but here debug informations when I connect :
`2021-01-15 15:09:24 DEBUG (MainThread) [custom_components.awox.config_flow] Processing device - {'objectId': 'UgkMej2G1E', 'address': '', 'modelName': 'SLCW13', 'friendlyName': 'Awox Dimmable Light (SLCW13-2301C9)', 'uuid': '24ab0aae-ea38-4f68-9436-84c1e1d19ed3', 'typedRoom': {'__type': 'Pointer', 'className': 'Room', 'objectId': 'JgpWWKqIuB'}, 'displayName': 'Awox Dimmable Light (SLCW13-2301C9)', 'room': 'Salon', 'owner': {'__type': 'Pointer', 'className': '_User', 'objectId': 'QwRLs3Oxim'}, 'syncable': True, 'provider': 'UPnPLight', 'vendor': 'Awox', 'type': '.wifi.light.switch.color.white.speaker.dimming.temperature.', 'createdAt': '2019-11-15T21:45:00.316Z', 'updatedAt': '2019-11-15T21:45:00.316Z', 'ACL': {'QwRLs3Oxim': {'read': True, 'write': True}}}
2021-01-15 15:09:24 WARNING (MainThread) [custom_components.awox.config_flow] Skipped device, missing macAddress - {'objectId': 'UgkMej2G1E', 'address': '', 'modelName': 'SLCW13', 'friendlyName': 'Awox Dimmable Light (SLCW13-2301C9)', 'uuid': '24ab0aae-ea38-4f68-9436-84c1e1d19ed3', 'typedRoom': {'__type': 'Pointer', 'className': 'Room', 'objectId': 'JgpWWKqIuB'}, 'displayName': 'Awox Dimmable Light (SLCW13-2301C9)', 'room': 'Salon', 'owner': {'__type': 'Pointer', 'className': '_User', 'objectId': 'QwRLs3Oxim'}, 'syncable': True, 'provider': 'UPnPLight', 'vendor': 'Awox', 'type': '.wifi.light.switch.color.white.speaker.dimming.temperature.', 'createdAt': '2019-11-15T21:45:00.316Z', 'updatedAt': '2019-11-15T21:45:00.316Z', 'ACL': {'QwRLs3Oxim': {'read': True, 'write': True}}}`

And I get this message from intergration : "[%key:common::config_flow::abort::no_devices_found%]"

Thanks

**Comment by fsaris** [comment]
No the integration only supports some of the bluetooth mesh lights for now. 

Only the lights where `type` starts with `.ble.tlmesh` currently work. The `.ble.zigbee.*` protocol also differs see #2 

Are the WiFi lights also able to be part of the bluetooth mesh?

Would be happy to look into this, but as I don't have such a wifi light it will be hard for me to get this to work.

**Comment by joffrey71** [comment]
How can I know that Wifi Light is part of the bluetooth mesh ?

I can handle my Wifi Light with Awox Smart Control Android App.

I will try to have a look in the code and see what informations Awox cloud returns.

**Comment by fsaris** [comment]
Had a look into the code of the Smart Control Android App and it seems this wifi light can't be controlled over Bluetooth.

For now I don't have adding support for these devices on my list, sorry. Mostly because I don't have one my self.

Will add a note to the readme that these wifi lights aren't supported with this integration

**Comment by Kees48** [comment]
Is it not possible to control the lights etc via WIFI using the plug plus switch from Awox? Synology DSM 7 does not support Bluetooth. It should be possible in HA over Wifi because it is now already working via the Awox app and/or Google
