### ISSUE TITLE
Works with Eglo Crosslink spot lights & external USB bluetooth bundle

### ISSUE THREAD

**Issue by michalpulda** [fsaris/home-assistant-awox#22]
Hi, not an issue -- just didn't know of a better way to let you know. Anyhow, I can confirm that the integration works with following lights (THANKS!):
- ESpot 120 (Eglo Crossling RGBW Spot with diameter of 120 mm, HW 4.30, firmware 2.2.6)
- ETriSpot 85 (set of 3 Eglo Crossling RGBW Spots with diameter of 85 mm, HW 4.31, firmware 2.2.6)
- ESpot 170 (Eglo Crossling RGBW Spot with diameter of 170 mm, HW 4.30, firmware 2.2.6)

Also, from the RPi 4B, where I run the HA, it is circa 10 meters to the lights. Integrated bluetooth on the RPi couldn't make it. So, I disabled it in the /boot/config.txt by adding a new line dtoverlay=disable-bt and connected a bluetooth adapter (any that has linux drivers/support works) on a USB extension cord  (this helps to reduce the radio noise generated by the RPi). It works now.

So, thanks again for the integration!

**Comment by fsaris** [comment]
Tnx for the feedback
