### ISSUE TITLE
Sync state with Eglo Crosslink remote

### ISSUE THREAD

**Issue by michalpulda** [fsaris/home-assistant-awox#23]
Hi, when I turn off the lights with Eglo Crosslink remote, the state is not updated in HA. Is there a way around it? Thanks

**Comment by fsaris** [comment]
Hi, it should update after a minute

**Comment by michalpulda** [comment]
Hi, yes, I can confirm that it updates somewhat between 20-40 seconds. First time I was not patient enough. Thanks!

**Comment by fsaris** [comment]
👍🏼
