### ISSUE TITLE
Awox CONNECT PLUG PLUS not found

### ISSUE THREAD

**Issue by stresskiller** [fsaris/home-assistant-awox#28]
hi ,  so far all eight ligt points are detected the only thing it doesn't find is my Awox CONNECT PLUG PLUS the wifi - bluetooth plug.

**Comment by djk314** [comment]
My plugs, motion sensor and remotes are not detected too, i think it's only awor lights here.

**Comment by fsaris** [comment]
Currently only lights are supported.

I personally don't have any other type of device so it's almost impossible for me to add support for other devices as I'm not able to test these.

**Comment by stresskiller** [comment]
fair enough , is there a way to find out what what id those sensors / plugs are using and can idiots/ non programing kind like me add those manualy in congif.yaml ?

**Comment by djk314** [comment]
The awox plug+ is a BL mesh bridge and a wifi bridge, it work with google assistant and alexa, so i can use "google assistant relay" addon to use the plug or the lamps, but it's slow and cannot see the state. The plug+ can monitor energy power and consumation too. No more info, i tried to ask Awox for more tech info or eventually an api, waiting...

**Comment by fsaris** [comment]
> fair enough , is there a way to find out what what id those sensors / plugs are using and can idiots/ non programing kind like me add those manualy in config.yaml ?

The id's aren't the problem. It's how to get/handle the bluetooth messages

**Comment by djk314** [comment]
can i catch msg's with a sniffer app on my phone may be ?

**Comment by fsaris** [comment]
> can i catch msg's with a sniffer app on my phone may be ?

Not sure it's that easy as all messages are encrypted.

You could decompile the android apk file and try to reverse engineer the commands etc. That's what I did for the other parts to.

**Comment by djk314** [comment]
I tried decompile but too mutch files... But i found this source https://github.com/guirem/plugin-blea  include a lot (all) devices in python source for Jeedom.

**Comment by fsaris** [comment]
On/off support over Bluetooth is now part of main. 

For power monitoring info I need some debug info/logs as I don't have a plus my self

**Comment by fsaris** [comment]
basis plug support is available now https://github.com/fsaris/home-assistant-awox/releases/tag/0.1.0
