### ISSUE TITLE
integration into home assistant disabled mobile app(s)

### ISSUE THREAD

**Issue by heron65** [fsaris/home-assistant-awox#29]
tested the integration today with my Awox Eglo warm white bulb.  on/off & dim worked well from home assistant.

tonight I found out that now the 3 mobile devices that had the native Awox app installed now will no longer control the bulb.

**Comment by fsaris** [comment]
Home Assistent just fakes to basic behavior of the app. It uses the same credentials etc. So controlling the lights from the app should still work (at least it works for me).

What could be is that timers etc are not kept after you controlled them from HA.

**Comment by heron65** [comment]
so I disabled the bulb (entity and device) from HA last night, and one of
the 3 mobiles was able to control the bulb via BT as before.  the other two
mobiles still responded "out of range"

I then switched off and back on the bulb (normal mains wall switch), and
was able to reconnect to it from the other 2 mobiles as well.  the existing
AWOX app schedule appeared to be retained (at least the dawn simulation
came on this morning as scheduled).

haven't yet gotten back to seeing if HA can join again.
I suspect that I couldn't control the bulb with the mobile apps because it
was in the middle of acting on an automation ?

will look some more tonight.

thank you!
Karin

**Comment by heron65** [comment]
ok. more from my testing today.
in any scenario where HA is involved, access is then disabled for other mobile devices running Awox app.

this includes HA on or off setting from the dashboard, or even just having the Eglo bulb on the dashboard and HA getting its status (which takes a few seconds).  Once HA has "been involved", then the Awox apps that had been working then no longer work with the error "out of range".

its like there is some state retained or some communication channel reserved from the bulb for HA that makes it look like the bulb is out of range to anyone else trying to control it.

in order to "break" the HA connection, I have to switch the wall switch on and off and "take the bulb back over from HA".

hopefully that helps a bit.  let me know if there are any test cases or scenarios you'd like me to try!

thanks again, Karin

**Comment by fsaris** [comment]
I'm afraid it's somehow a limitation of the bluetooth connection.

For me the app keeps working correctly (android). But I only have 1 app that I test and 15 lights in the bluetooth mesh. Maybe a light can only be connected to 1 controller device (app or HA). 


The idea (at least for me : smile) of this integration is to control the lights from HA and drop the use of the app. Also the timer options etc shouldn't be set in the app but let HA do this. This way you can also incorporate your other lights and devices. 

Currently I only use the app as fallback and for updating the firmware

**Comment by heron65** [comment]
it'll encourage me to migrate housemate from awox app to HA companion app on the mobile :)

**Comment by fsaris** [comment]
👍🏼
