### ISSUE TITLE
bulbs not connecting anymore (unavailable)

### ISSUE THREAD

**Issue by stefbulcke** [fsaris/home-assistant-awox#36]
Hi,

I was able to install EGLO bulbs  (2.6.25) and for a while all went well.  So thanks for the integration!

However a few days ago  I've lost power and since then I'm unable to address the bulbs via HA.  I've restarted and reinstalled everything from scratch (integration, even deleted the bulbs from the original AWOX Smart Control app,...).  Strange thing is the lamps do show up again in the original Awox app, the are controllable there (so bluetooth is working fine), after reinstalling the integration, they are found and added nicely by HA, but whatever I try, the stay "unavailable" as an entity. 

Any idea's?

grtz

**Comment by fsaris** [comment]
Can you set logging to debug and check what the logs say?

https://github.com/fsaris/home-assistant-awox#troubleshooting

**Comment by stefbulcke** [comment]
Dag Frans,  

Kan ook in het Nederlands als je dat wenst… ;-)

Enclosed I’ll send the logfile which I had installed already.

It seems after all it is a bluetooth connection problem.   However the bulbs are working fine with the original app.
It seems the device is always “busy” and therefor the connection can not be made?  I’m no developer, just guessing...

Thanks!
Stef

**Comment by stefbulcke** [comment]
Did that already...

**Comment by fsaris** [comment]
Laten we het in het Engels houden zodat andere er evt ook iets aan hebben 😄 

I would start with a reboot your HA (host) 

Check if HA is then able to connect to the bluetooth device/module. It's not the light that's busy but the bluetooth dongle/chip/etc in your HA system
