### ISSUE TITLE
Home Assistant on Raspberry 4 does not show AWOK integration

### ISSUE THREAD

**Issue by ww9020** [fsaris/home-assistant-awox#38]
SORRY - NOW IT WORKS
Maybe it takes some time to do the internal config on the PI.

Hi smart home fans,

I followed the steps in read.me:

I installed the awox integration via HACS in home assistant, the files are in custom_components/awox (checked), 
restart was done but 

configuration - add integration 
does not show the awox integration.

Does anybody know a solution.
Thank you very much in advance!
Walter from Austria

**Comment by fsaris** [comment]
Maybe try to refresh the browser
