### ISSUE TITLE
Problems with two Eglo spots

### ISSUE THREAD

**Issue by uwecash** [fsaris/home-assistant-awox#39]
Hi,

i have two Eglo RGBW spots and an Eglo Smart Plug Plus. When I add the integration, both entities are displayed, but only one spot works at a time! The other is always shown as unavailable (always the same work and the other not).
I can do what I want ... have already deleted / installed the integration 20 times, reset the lights in the app 30 times, etc ... etc ...
I'm at the end of my nerve!
Before I bought the second and added it, the first worked. And it is exactly this that no longer works.

**Comment by fsaris** [comment]
Are the two lights in reach of each other?

HA connects to the first light and assumes that light can reach the next one to passthrough the commands
