### ISSUE TITLE
integration cannot be loaded

### ISSUE THREAD

**Issue by ZTHawk** [fsaris/home-assistant-awox#41]
Hello,

I am running HA on a raspbianOS. I have installed the bluetooth dependencies.
I have added this integration successfully via HACS.

But when trying to add it in HA I get this issue: "Config flow could not be loaded"
Which I can only dismiss by clicking OK.

If I try to add it again I get an endless loop of "Adding integration..." (even after 10min it does not disappear).

I have also added the additional logs in configuration.yaml. But all I got was this message:
2021-04-30 12:11:52 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration awox: No module named 'Crypto'

**Comment by fsaris** [comment]
had similar issue yesterday in my new test env. Looks like some requirements where changed in the core.

Next release should fix this.
