### ISSUE TITLE
EGLOPanel sometimes is there sometimes not

### ISSUE THREAD

**Issue by dabepp** [fsaris/home-assistant-awox#43]
Hi!
The integration usually works fine. But sometimes the EGLOPanel (120x30) is not available in HASS but in the AWOX App.
But right now the Panel is available in HASS but not in the AWOX App (See Screenshot).

Is this a known issue/limitation? Is there anything I can do to let HASS take the lead all the time?

KR and thanks for the integration!
![image](https://user-images.githubusercontent.com/28548283/116853382-3dad3c80-abf6-11eb-88e7-555f94e07dc0.png)

**Comment by fsaris** [comment]
I currently still not able to get it fully reliable. Mostly due some issues in bluepy. Python and bluetooth are currently not that best friends when it comes to long living connections.

One improvement could be a new release of https://github.com/IanHarvey/bluepy
An other that's on my list to try is closing the bluetooth after each operation (with some delay to proces concurring actions on same connection when possible). But this will most likely give a delay when controlling the lights.

So first let's hope a new version of bluepy gets released soon

**Comment by dabepp** [comment]
Keep it up! Thank you! :-)
I mean it is in the kitchen and the panel is usually switched on and off via the switch on the wall... Just from time to time (Sitting on the sofa and watching TV and kitchen lights are still on) it is kind of handy. But nevertheless to have some kind of integration at all is highly appreciated! :-)

**Comment by fsaris** [comment]
Ported the most important improvements to the integration self as there is still no new release off bluepy.
