### ISSUE TITLE
shell=True in subprocess

### ISSUE THREAD

**Issue by fablocke** [fsaris/home-assistant-awox#45]
Hi,
thank you for this project!
I noticed something that is a little bit smelly:

shell=True can lead to a shell injection and should be avoided.
https://docs.python.org/3/library/subprocess.html#security-considerations

https://github.com/fsaris/home-assistant-awox/blob/e990f897ca9b41e513e2b88181da8c6b9b3f5856/custom_components/awox/bluetoothctl.py#L19

**Comment by fsaris** [comment]
If I'm not mistaken this is needed because the process needs to run a command in the shell
