### ISSUE TITLE
No "Install" button after adding repository to HACS

### ISSUE THREAD

**Issue by benhei** [fsaris/home-assistant-awox#49]
Thanks for this great project. I run 3 Awox lights and would love to control them from HA.

Following the official instructions, I arrived at:
![image](https://user-images.githubusercontent.com/916316/135314924-058744eb-fddf-4273-afbb-f0217ee3c780.png)

HA Core Version: core-2021.9.7
HACS Integration version: 1.15.2

Any hints how to get the "Install" button to appear?

**Comment by fsaris** [comment]
This screen means you installed it already. Now head over to integrations and add the awox integration.

Here a shortcut https://my.home-assistant.io/redirect/config_flow_start/?domain=awox

**Comment by benhei** [comment]
Indeed. Now everything works. Fantastic work!
