### ISSUE TITLE
Connot connect to EGLO panel

### ISSUE THREAD

**Issue by danieldur** [fsaris/home-assistant-awox#51]
Hello,

Because my lamp was no longer active in the AWOX Android app, I decided to delete it and add it back. This also meant resetting the lamp itself.

After this whole ordeal, when I delete and add back the AWOX integration I get the following error in the HA logs:

This error originated from a custom integration.

Logger: custom_components.awox.awox_mesh
Source: helpers/update_coordinator.py:219
Integration: AwoX MESH control (documentation, issues)
First occurred: 19:05:55 (8 occurrences)
Last logged: 20:07:17

Error fetching awox data: No device connected

The lamp works perfectly with the AWOX Android app and with its own hardware Bluetooth remote.
I'm using a Pi 4 as the HA host and it hasn't changed its location. The entity becomes unavailable directly after configuring the integration. Restarting the Pi doesn't help.

Any idea why this would happen?
Thanks!

**Comment by fsaris** [comment]
@danieldur the pastbin doesn't load for me currently

**Comment by danieldur** [comment]
Here is a new log: https://pastebin.com/AdabXDpq

**Comment by fsaris** [comment]
logs do not hold that much awox info. Could you set logging to:

```
logger:
  default: error
  logs:
     custom_components.awox: debug
```

I'm particular interested in the lines around `Search for AwoX devices to find closest (best rssi value) device` 

And after that the connect attempt

**Comment by danieldur** [comment]
Here are the requested logs: https://pastebin.com/cswydXcc
Thanks for your efforts!

**Comment by fsaris** [comment]
What I find strange is that your `mesh_name` doesn't seem to match the name of the light that comes back from the Bluetooth scan (`devices ... mac:..., name:..., rssi:...`). For others I see a match between those.

Could you maybe again remove the integration and set it up again? I'm curious what the response from Awox is during setup. This should also be written to the log.

**Comment by danieldur** [comment]
One more log: https://pastebin.com/BUBfW5Qk
The one thing I did recently was to set the light up from scratch and add it to the app. I guess something might have gone wrong. Probably I should reset it again tomorrow.

**Comment by danieldur** [comment]
I've reset the lamp once more and now it works.
Thanks for all the help!

**Comment by fsaris** [comment]
Did the Bluetooth name of the device change?
