### ISSUE TITLE
awox lights shows in the panel but the on/off button is greyed out

### ISSUE THREAD

**Issue by lcarpineto** [fsaris/home-assistant-awox#53]
Hi,
I could install the awox module,all lights have been recognised but I cannot control them.
Below the  log, any help?
thanks
[log.txt](https://github.com/fsaris/home-assistant-awox/files/7779621/log.txt)

**Comment by fsaris** [comment]
Hi,

The integration is currently only able to connect to the `.ble.tlmesh.*` lights (see also https://github.com/fsaris/home-assistant-awox/issues/2).

Is your Home assistant system in the Bluetooth range of one of these `.ble.tlmesh.` lights? Reading your logs is seems that all the devices are out of range.

**Comment by cloudycgn** [comment]
Hi,

i had the exact the same issue, some weeks ago, during setup my home assistant with this plugin. In my case using a different Bluetooth-Interface worked as solution. For any reason the normal Bluetooth-Interface in my home server wasn't able to connect to my LED-panels. Then I used the Bluetooth-Interface of of my "Teufel Audio Headset" and connected it to the server and it worked out as perfect solution.

Since then I am able to control 9 LED-Panels and 2 Power Plugs with home-assistant and this plugin without any further problems.

Good luck

**Comment by lcarpineto** [comment]
Hi fsaris, 
some of the devices are well within the range (2 or 3 meters) . I am using the raspberry 4 with the latest ha version. How can I check if the bluethoot is properly working? The "awox mesh" seems to connectect to various light. 
![image](https://user-images.githubusercontent.com/74138912/147464632-b10af4e2-3e50-4fd9-8010-8f1f9685d511.png)

Hi cludycng, what is the procedure to use another bluetooth interface, I might have quite few around.
thanks

**Comment by cloudycgn** [comment]
@lcarpineto I think this depends on your hardware configuration, I am using an Desktop Ubuntu Server, you wrote, that you use Raspberry, I don't know how to change bluetooth interface on this device. Perhaps you might try just to plug in an USB-Bluetooth-Device and give it a try ;) You are using Ego Connect LED Panels as well?

**Comment by fsaris** [comment]
> Hi fsaris, some of the devices are well within the range (2 or 3 meters) . I am using the raspberry 4 with the latest ha version. How can I check if the bluethoot is properly working? The "awox mesh" seems to connectect to various light. ![image](https://user-images.githubusercontent.com/74138912/147464632-b10af4e2-3e50-4fd9-8010-8f1f9685d511.png)
> 

So the integration is able to connect to some of the lights. Can you check the status of these light. Are they always un-available?

**Comment by cob94440** [comment]
Hi,
For me still this error :
`Failed to decrypt package [key: bytearray(b'\xc9\xbc\xc8?w\xe3\xae"\xd2\xfa\x93\xf9\x8b\xd5vW'), data: b'\x82\xa7\xc0nK \xb8\x8b\xf4\xa1\x012\x1d\xe8Z\n\xf1\xff\xff`']`

**Comment by fsaris** [comment]
could you test the beta version and when still running into issues enable debug logging and attach the log here? https://github.com/fsaris/home-assistant-awox#troubleshooting

**Comment by Slion** [comment]
Similar issue with at least one light using v0.1.3b3.
See: https://github.com/fsaris/home-assistant-awox/issues/59#issuecomment-1250076732

**Comment by fsaris** [comment]
Are the lights in reach of each other? If you set logging to debug it should give some more info about the mesh status. The mesh will send notifications about each known device and notifications about the status of the device.

Maybe try to move the device and/or power it off/on to force it to reconnect to the mesh.

Controlling them with awox app works?

**Comment by Slion** [comment]
> If you set logging to debug

How to I do that. Where can I find the logs then?

> Maybe try to move the device

Can't really do that. It's a ceiling lamp.

> power it off/on to force it to reconnect to the mesh.

Tried that many times.

> Controlling them with awox app works?

Usually yes. But that one light that's causing me trouble I can turn it off when it is on from the app but then I can't turn it back on again. I just loose the connection.

Things is it is part of a group in the app. I've got the Hallway group with two lights, Entrance and Floor and the Wifi Hub switch. The Entrance never comes online in the integration but the Floor works just fine. If I had to take a guess there is something going one because of the grouping. Even the app gets confused, sometimes if I turn one of them off or both I can't turn them back on. Though they are both still responding to the remote.

**Comment by fsaris** [comment]
Logs can be found going to Settings -> System -> Logs

**Comment by Slion** [comment]
All devices do come online eventually even though they sometimes drop out but that Entrance device never comes online for some reason even though it is rather central to the mesh:

![image](https://user-images.githubusercontent.com/6508892/190894303-8411ec35-6d1f-4fb6-8600-a0709f562afd.png)

Here is what I got in the logs:
```
exception Timed out connecting to a4:c1:38:84:52:bc after 15 seconds.
10:46:22 – (ERROR) AwoX MESH control (custom integration) - message first occurred at 10:45:44 and shows up 3 times
Timed out connecting to a4:c1:38:84:52:bc after 15 seconds.
10:46:22 – (ERROR) AwoX MESH control (custom integration) - message first occurred at 10:45:44 and shows up 3 times
Timeout fetching awox data
10:45:45 – (ERROR) AwoX MESH control (custom integration)
Failed to stop scan: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f6d1a16c0> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): 'evice 64:E7:D8:30:43:51 RSSI: -89\r\n[\x01\x1b[0;92m\x02NEW\x01\x1b[0m\x02] Device 7D:0D:0D:5A:62:1F 7D-0D-0D-5A-62-1F\r\n' before (last 100 chars): 'evice 64:E7:D8:30:43:51 RSSI: -89\r\n[\x01\x1b[0;92m\x02NEW\x01\x1b[0m\x02] Device 7D:0D:0D:5A:62:1F 7D-0D-0D-5A-62-1F\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 98 child_fd: 43 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF
10:45:25 – (ERROR) AwoX MESH control (custom integration)
Failed to get available devices: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f6d1a16c0> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): 'd3 f9 73 5a ..C/SIn.H..z..sZ\r\n c7 1b 01 60 10 35 ba ...`.5. \r\n' before (last 100 chars): 'd3 f9 73 5a ..C/SIn.H..z..sZ\r\n c7 1b 01 60 10 35 ba ...`.5. \r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 98 child_fd: 43 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF
10:44:55 – (ERROR) AwoX MESH control (custom integration)
Failed to start scan: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f6d1a16c0> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): '\x1b[0m\x02] Device 48:B0:2D:5D:C3:61 RSSI: -84\r\n[\x01\x1b[0;93m\x02CHG\x01\x1b[0m\x02] Device 48:B0:2D:5D:C3:61 RSSI: -88\r\n' before (last 100 chars): '\x1b[0m\x02] Device 48:B0:2D:5D:C3:61 RSSI: -84\r\n[\x01\x1b[0;93m\x02CHG\x01\x1b[0m\x02] Device 48:B0:2D:5D:C3:61 RSSI: -88\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 98 child_fd: 43 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF
10:44:05 – (ERROR) AwoX MESH control (custom integration)
```

**Comment by fsaris** [comment]
@Slion okay the scan process gives some issues. But that doesn't prevent the integration to connect to some of your devices.

Could you also post the logs from when the integration is running for a while? Then it will post some more info about status messages etc.

Are you sure no awox app is currently connected to the light that isn't responding? It can not handle multiple connections

**Comment by Slion** [comment]
Sorry I just realised only errors where shown there and I needed to expand the logs.
Here is a section of 5mn logs where no much should have been happening.
The device that never comes online is called Entrance:

[awox-logs.txt](https://github.com/fsaris/home-assistant-awox/files/9593527/awox-logs.txt)

**Comment by Slion** [comment]
> Are you sure no awox app is currently connected to the light that isn't responding? It can not handle multiple connections

Well I was not using the app. I almost never use the app. However all lights have their own Eglo remote which are always very responsive. Never have any issue with those. As soon as I power a light the Eglo remote works. If we could get that integration to work like the Eglo remotes that would be fantastic. 

Once the device is online I can get both Harmony and Eglo remotes to work together, they don't seem to conflict with each other.

However it seems to take a while for devices to come online after they are powered on. Not sure what's the expected delay there. Again the Eglo remotes don't have such issues maybe because they just send commands without trying to handshake or something.

**Comment by fsaris** [comment]
> However it seems to take a while for devices to come online after they are powered on. Not sure what's the expected delay there. Again the Eglo remotes don't have such issues maybe because they just send commands without trying to handshake or something.

The remotes are directly communicating with the lights    and indeed handshake is probably not happening.

When lights come online again it can take around 30 seconds untill they reported the state to HA
