### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by masterdraco** [fsaris/home-assistant-awox#55]
Hi
i have a problem when loggin in to the awox integration
it keeps saying wrong username or password.

i have been loggin in and out of the app on my phone so i know it is the right email and password im using

any suggestions i could try ?

Logger: custom_components.awox.config_flow
Source: custom_components/awox/config_flow.py:140
Integration: AwoX MESH control (documentation, issues)
First occurred: 17.52.21 (1 occurrences)
Last logged: 17.52.21

Can not login to AwoX Smart Connect [Login failed - Invalid username/password.]

**Comment by masterdraco** [comment]
turns out there are two awox programs
Awox smart connect
and
awox smart home

works fine after installing AWOX Smart Connect

**Comment by fsaris** [comment]
Good to know about this 2th app. Glad it works now
