### ISSUE TITLE
Lights are not available in HA

### ISSUE THREAD

**Issue by gerendasp** [fsaris/home-assistant-awox#58]
I've done the setup for the Awox Mesh integration, and I could log in to the Awox account, my Lights are added. I have a mesh created by the Smart Plug, and 2 of my lights are in bluetooth range, but I can not control them.

HA is running on Raspberry Pi 4.

Log1:
_Logger: custom_components.awox.awox_mesh
Source: custom_components/awox/awox_mesh.py:119
Integration: AwoX MESH control (documentation, issues)
First occurred: 10:22:59 (8 occurrences)
Last logged: 10:42:49
Fetching RSSI failed -_

Log2:
_Logger: custom_components.awox.bluetoothctl
Source: custom_components/awox/bluetoothctl.py:37
Integration: AwoX MESH control (documentation, issues)
First occurred: 10:21:33 (9 occurrences)
Last logged: 10:44:10_

_Failed to start scan: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f95aa3550> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): ' . \r\n[\x01\x1b[0;93m\x02CHG\x01\x1b[0m\x02] Device 26:17:72:CF:32:8B RSSI: -42\r\n' before (last 100 chars): ' . \r\n[\x01\x1b[0;93m\x02CHG\x01\x1b[0m\x02] Device 26:17:72:CF:32:8B RSSI: -42\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 343 child_fd: 29 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF
Failed to start scan: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f9617ff40> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): '00 00 00 00 ................\r\n 00 . \r\n' before (last 100 chars): '00 00 00 00 ................\r\n 00 . \r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 372 child_fd: 27 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF
Failed to start scan: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f95a3aeb0> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): '08:B4 ManufacturerData Value:\r\n 53 4d 4f aa 58 SMO.X \r\n' before (last 100 chars): '08:B4 ManufacturerData Value:\r\n 53 4d 4f aa 58 SMO.X \r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 401 child_fd: 29 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF
Failed to start scan: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f95a00a00> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): ' . \r\n[\x01\x1b[0;93m\x02CHG\x01\x1b[0m\x02] Device 6D:80:75:E9:29:74 RSSI: -77\r\n' before (last 100 chars): ' . \r\n[\x01\x1b[0;93m\x02CHG\x01\x1b[0m\x02] Device 6D:80:75:E9:29:74 RSSI: -77\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 430 child_fd: 48 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF
Failed to start scan: Timeout exceeded. <pexpect.pty_spawn.spawn object at 0x7f9afc2c70> command: /usr/bin/bluetoothctl args: [b'/usr/bin/bluetoothctl'] buffer (last 100 chars): 'HG\x01\x1b[0m\x02] Device 6D:80:75:E9:29:74 RSSI: -91\r\n[\x01\x1b[0;92m\x02NEW\x01\x1b[0m\x02] Device 02:ED:A9:02:08:B4 E3.5BT\r\n' before (last 100 chars): 'HG\x01\x1b[0m\x02] Device 6D:80:75:E9:29:74 RSSI: -91\r\n[\x01\x1b[0;92m\x02NEW\x01\x1b[0m\x02] Device 02:ED:A9:02:08:B4 E3.5BT\r\n' after: <class 'pexpect.exceptions.TIMEOUT'> match: None match_index: None exitstatus: None flag_eof: False pid: 459 child_fd: 29 closed: False timeout: 30 delimiter: <class 'pexpect.exceptions.EOF'> logfile: None logfile_read: None logfile_send: None maxread: 2000 ignorecase: False searchwindowsize: None delaybeforesend: 0.05 delayafterclose: 0.1 delayafterterminate: 0.1 searcher: searcher_re: 0: re.compile('bluetooth') 1: EOF_

**Comment by fsaris** [comment]
can you enable debug logging and post the logs here? https://github.com/fsaris/home-assistant-awox#troubleshooting

**Comment by mindbuilder18** [comment]
Hello i instaled the integration trew the Hacs extension but at every startup i get tihs masage from the Awox integration did any one of you now what i have to do i´m completly new to homeassistant : 
![grafik](https://user-images.githubusercontent.com/108027172/190867554-a3883250-a6cf-4bec-8557-23d44e098e98.png)

Thank you

**Comment by fsaris** [comment]
The warning is just a notice.

The error is fixed with latest version (just released it).

**Comment by mindbuilder18** [comment]
OK but I can Not control the lights

**Comment by fsaris** [comment]
Can you enable debug logging and post the logs here?

**Comment by mindbuilder18** [comment]
Yes i can try but i don't now how to do this or where i can edit the yaml file

**Comment by fsaris** [comment]
@mindbuilder18 see https://www.home-assistant.io/docs/configuration/#editing-configurationyaml

You can also go to `Developer tools -> Services` and send 
```
service: logger.set_level
data:
  custom_components.awox: debug
```

That will temporary enable logging until next restart of HA

**Comment by mindbuilder18** [comment]
![Screenshot 2022-09-18 192528](https://user-images.githubusercontent.com/108027172/190920327-c55b56d1-4f1c-4df9-bba3-7273bc24d8aa.png)

**Comment by mindbuilder18** [comment]
![Screenshot 2022-09-18 192528](https://user-images.githubusercontent.com/108027172/190920365-92ac5a12-de6d-4b48-9c89-a9da06425b29.png)

I get an alart if i try to actavate the logs "I hope you can read the report my mother language is german and because of this my Home Asisstant system is set to german

**Comment by mindbuilder18** [comment]
![grafik](https://user-images.githubusercontent.com/108027172/190922159-b1b77b30-0b9d-47ef-9943-f78ca261a1b6.png)


or what have I to do now ?

**Comment by mindbuilder18** [comment]
i can not see any directory witch is labeld debug ??

**Comment by fsaris** [comment]
> ![Screenshot 2022-09-18 192528](https://user-images.githubusercontent.com/108027172/190920365-92ac5a12-de6d-4b48-9c89-a9da06425b29.png)
> 
> I get an alart if i try to actavate the logs "I hope you can read the report my mother language is german and because of this my Home Asisstant system is set to german

You could try to switch to UI mode. Select the log level service and paste `custom_components.awox: debug` as value

**Comment by fsaris** [comment]
> ![grafik](https://user-images.githubusercontent.com/108027172/190922159-b1b77b30-0b9d-47ef-9943-f78ca261a1b6.png)
> 
> or what have I to do now ?

Open the `configuration.yaml` file. Add the lines from the readme regarding the debug config. Validate the configuration and restart HA

**Comment by mindbuilder18** [comment]
![grafik](https://user-images.githubusercontent.com/108027172/190922405-103fd503-3c9b-4674-9864-55c39c7a70c1.png)

Like this right?

**Comment by mindbuilder18** [comment]
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 20:21:49 (3 occurrences)
Last logged: 20:22:13

    Unable to install package bluepy>=1.3.0: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [8 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running bdist_wheel running build running build_py Working dir is /tmp/pip-install-hsrc2jio/bluepy_5b51b2535b6a413dba5e030e122e1775 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for bluepy error: subprocess-exited-with-error × Running setup.py install for bluepy did not run successfully. │ exit code: 1 ╰─> [10 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running install /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py Working dir is /tmp/pip-install-hsrc2jio/bluepy_5b51b2535b6a413dba5e030e122e1775 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> bluepy note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.
    Unable to install package bluepy>=1.3.0: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [8 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running bdist_wheel running build running build_py Working dir is /tmp/pip-install-f4bhg5sf/bluepy_dd6ea869a7cc4742be37a693da653817 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for bluepy error: subprocess-exited-with-error × Running setup.py install for bluepy did not run successfully. │ exit code: 1 ╰─> [10 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running install /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py Working dir is /tmp/pip-install-f4bhg5sf/bluepy_dd6ea869a7cc4742be37a693da653817 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> bluepy note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.
    Unable to install package bluepy>=1.3.0: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [8 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running bdist_wheel running build running build_py Working dir is /tmp/pip-install-bq53c4ye/bluepy_a29faf503dce403dbda07cbdd654e5c1 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for bluepy error: subprocess-exited-with-error × Running setup.py install for bluepy did not run successfully. │ exit code: 1 ╰─> [10 lines of output] /usr/local/lib/python3.10/site-packages/setuptools/dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running install /usr/local/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build running build_py Working dir is /tmp/pip-install-bq53c4ye/bluepy_a29faf503dce403dbda07cbdd654e5c1 execute make -C ./bluepy clean error: [Errno 2] No such file or directory: 'make' [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure × Encountered error while trying to install package. ╰─> bluepy note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.


 Logger: homeassistant.setup
Source: setup.py:184
First occurred: 20:22:13 (1 occurrences)
Last logged: 20:22:13
Setup failed for custom integration awox: Requirements for awox not found: ['bluepy>=1.3.0'].

**Comment by fsaris** [comment]
@mindbuilder18 you need to use the latest version of this integration https://github.com/fsaris/home-assistant-awox/releases/tag/0.1.3

**Comment by mindbuilder18** [comment]
OK i will try it out later thank you

**Comment by mindbuilder18** [comment]
It loks like its working now but i think my LEDs are not in range. Do you know a way to extend the Bluotooth signal

**Comment by fsaris** [comment]
@mindbuilder18 use a Bluetooth USB dongle with some longer USB cable. The onboard devices have not great reach

**Comment by mindbuilder18** [comment]
I ouse a USB dongle but the Server ist in a difren rom
