### ISSUE TITLE
Can't configure Awox Mesh in HA

### ISSUE THREAD

**Issue by GermanGiTter** [fsaris/home-assistant-awox#61]
Hi,

I can't complete the integration in HA as it seems I have this problem: 
homeassistant.requirements.RequirementsNotFound: Requirements for awox not found: ['bluepy>=1.3.0'].

But on the same time I get this error message:
Unable to install package bluepy>=1.3.0: error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully
-> which was alread addressed here: https://github.com/home-assistant/core/issues/74534

So how can I install the AwoX integration, when I am not able to install (or it's not anymore part of HassOS) the pre-required pybluez anymore ?

Thank you in advance!

**Comment by fsaris** [comment]
I'm currently working on an update to make the integration compatible with the new HA versions see #59

Closing this issue as it's a duplicate
