### ISSUE TITLE
Bluetooth Proxy

### ISSUE THREAD

**Issue by JbbDE** [fsaris/home-assistant-awox#67]
Is there a plan to make this work with the new home assistant bluetooth proxy?

**Comment by fsaris** [comment]
Currently this isn't possible as the Awox devices do not use proper BLE standards.

Trying to contact awoxi/eglo but not sure if that will be successful

**Comment by ZdravecG** [comment]
Does this mean, that also a bluetooth repeater cannot help? I was looking at https://esphome.io/, but there is no support and thinking of writing a custom worker for https://github.com/zewelor/bt-mqtt-gateway, but not sure, if the gateway can help.

**Comment by fsaris** [comment]
Due to the Bluetooth issues in latest HomeAssistant versions and the fact that the AwoX BLE mesh doesn't respect the BLE standards I start working on a esphome based component to replace this integration https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub

**Comment by 4D4M-Github** [comment]
Dear Frans,
first of all, thanks for your efforts. Also, I have an Olimex ESP32-POE-EA device that I wanted to use as a bluetooth proxy especially for EGLO lamps. However, at the moment I have not been able to establish a connection with your old integration, but I would be happy to help you test the MQTT version. I tried to flash it but couldn't really get past the compilation. How could I help you? 

Thanks in advance!

**Comment by fsaris** [comment]
@4D4M-Github I moved the discussion about getting the esphome component running to https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/issues/5
