### ISSUE TITLE
Some lights not being detected

### ISSUE THREAD

**Issue by dom11990** [fsaris/home-assistant-awox#68]
Hi, thanks for your efforts in bringing support for these lights to HA! Unfortunately, I've had limited success getting it to work 100%. My phone seems to be able to detect all of them just fine with the AwoX app, but in HA, two are always missing (and they are not even the farthest away). Missing in the sense that they are unavailable. The devices were imported fine with the correct names etc, but I can never control them. I've tried deleting the integration, renaming lights in the AWoX app and reimporting, which pulled in the correct new names but I still couldnt control them. What can I do to troubleshoot this? im on the latest 1.45b build and I've attached a log. Thanks for any help!
[log.txt](https://github.com/fsaris/home-assistant-awox/files/9739253/log.txt)

**Comment by dom11990** [comment]
I did a hard reset on the lights. I noticed that the two that weren't being detected were installed several weeks after the first set. Although they all have the same model and firmware, somehow this seemed to be an issue. After I set everything up again everything works. Great tool!

**Comment by fsaris** [comment]
👍🏼
