### ISSUE TITLE
Awox HomeControl

### ISSUE THREAD

**Issue by robgardien** [fsaris/home-assistant-awox#71]
I have 2 crosslink 2 Eglo lights, I can't find my lights using the Awox Smart Control app but the Awox HomeControl app does work. Is it possible to use this app with the home assistant awox integration?

**Comment by fsaris** [comment]
Are they Bluetooth or ZigBee lights?

**Comment by robgardien** [comment]
They use both bluetooth and zigbee, the app uses bluetooth

**Comment by imilchev** [comment]
Yup, same here. Willing to debug it but not sure how to at this point

**Comment by fsaris** [comment]
This integration uses the Awox Smart Control app API to fetch some needed hardware info and keys. So if you don't see the lights in that app it will probably not work.

You could also check if they are supported by https://www.zigbee2mqtt.io/ or https://github.com/zigpy/zigpy

**Comment by fsaris** [comment]
if your light have ZigBee support I suggest going for that. It's a lot more stable than BLE.
