### ISSUE TITLE
Raising Retry count enables connecting to the lamp at all

### ISSUE THREAD

**Issue by Chaosflo** [fsaris/home-assistant-awox#78]
I tried to raise the retry count to more than 3 (I choose 50).
https://github.com/fsaris/home-assistant-awox/blob/03b1d327edc5f751b044183b7cdd224d16bfa8f0/custom_components/awox/awox_mesh.py#L272

This helped me to connect to the lamp at all.
Before that the Timeout mentioned here #72 delayed this to several minutes or hours. (noticed in the Logbook of the Lamp)

What I noticed too that the timeout is related to the experimental features enabled in HassOs
I created a bug [there](https://github.com/home-assistant/operating-system/issues/2290) 
This leads to the weird thing of the this error
Failed to connect: org.bluez.Error.Failed le-connection-abort-by-local

Which I think so will not forwared into the logs, instead it hangs and will timeout after 15s

**Comment by fsaris** [comment]
so there is some kind of watchdog process that disconnects the connection before the command could be processed?

**Comment by Chaosflo** [comment]
IDK why, didn't found the reason still
Fact is sadly there is not really a change between experimental features on or off.|
In the mentioned issue there was a description how to change it for HassOS

BUT, the speed is better, not by much but still.

Sadly in my environment its pretty much unusable
It works 1 out of 100 times.
I can't connect to it, ends everytime with a timeout
I tried another bluetooth adapter still.

Just out of curiosity, why did you choose against the homeassistant bleak library for this task?
I am writing my own integration for another product and it works flawlessly so far.
There  is a thing called bleak retry connector which helped me, reduce the timeouts to zero

Maybe this would help you =?

**Comment by fsaris** [comment]
Tried to switch to bleak but sadly the awox devices do not follow the BLE specs. Notification handling doesn't work and then we can’t check the current device status.

See also https://github.com/fsaris/home-assistant-awox/issues/67#issuecomment-1272374026

**Comment by fsaris** [comment]
Closed, see #110 for more info
