### ISSUE TITLE
Warnings and errors using the integration

### ISSUE THREAD

**Issue by dasEtwasmitPunkten** [fsaris/home-assistant-awox#79]
My HA throws some warnings and errors on startup and in irregular intervals. The light works well as far as I can see.

> Logger: homeassistant.util.async_
> 
> Source: util/async_.py:180
> First occurred: 3:54:07 PM (1 occurrences)
> Last logged: 3:54:07 PM
> 
> Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for awox doing blocking calls at custom_components/awox/awox_mesh.py, line 346: devices = await DeviceScanner.async_find_devices(hass=self.hass, scan_timeout=20)`
> 
> `This error originated from a custom integration.
> 
> Logger: custom_components.awox.awoxmeshlight
> Source: custom_components/awox/awoxmeshlight/__init__.py:196
> Integration: awox (documentation, issues)
> First occurred: 3:54:24 PM (1 occurrences)
> Last logged: 3:54:24 PM
> 
> Timed out connecting to a4:c1:38:xx:xx:xx after 15 seconds.

MAC-Address? anonymized.

> This error originated from a custom integration.
> 
> Logger: custom_components.awox.awox_mesh
> Source: custom_components/awox/awoxmeshlight/__init__.py:108
> Integration: awox (documentation, issues)
> First occurred: 3:54:24 PM (1 occurrences)
> Last logged: 3:54:24 PM
> 
> exception Timed out connecting to a4:c1:38:xx:xx:xx after 15 seconds.
> Traceback (most recent call last):
>   File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 101, in connect
>     with self._receiver.event("connect", timeout):
>   File "/usr/local/lib/python3.10/contextlib.py", line 142, in __exit__
>     next(self.gen)
>   File "/usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/gatttool.py", line 191, in event
>     self.wait(event, timeout)
>   File "/usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/gatttool.py", line 157, in wait
>     raise NotificationTimeout()
> pygatt.exceptions.NotificationTimeout: None
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/awox/awox_mesh.py", line 324, in _async_connect_device
>     if await self.hass.async_add_executor_job(device.connect):
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 196, in connect
>     self.btdevice = self.adapter.connect(self.mac, timeout=15)
>   File "/config/custom_components/awox/awoxmeshlight/__init__.py", line 108, in connect
>     raise NotConnectedError(message)
> pygatt.exceptions.NotConnectedError: Timed out connecting to a4:c1:38:xx:xx:xx after 15 seconds.

MAC-Address? anonymized.

> 
> This error originated from a custom integration.
> 
> Logger: custom_components.awox.awox_mesh
> Source: custom_components/awox/awox_mesh.py:262
> Integration: awox (documentation, issues)
> First occurred: 3:54:24 PM (1 occurrences)
> Last logged: 3:54:24 PM
> 
> Command failed, retry 1

> This error originated from a custom integration.
> 
> Logger: custom_components.awox.awox_mesh
> Source: helpers/update_coordinator.py:201
> Integration: awox (documentation, issues)
> First occurred: 3:54:27 PM (1 occurrences)
> Last logged: 3:54:27 PM
> 
> Timeout fetching awox data

**Comment by fsaris** [comment]
Tnx for the feedback. Will check if I can improve something

**Comment by Anashost** [comment]
Got exact same issue. Lamp seems to work but sometimes doesn't respond :(
Lamp Model:
ESMLm-C5-E14 . Version 2.6.30 (HW 4.52)

**Comment by dasEtwasmitPunkten** [comment]
I have now noticed a short delay before a command is executed. At the same time I had the error messages in the log again. So the lamp seems to be unreachable or disconnected from time to time.

**Comment by fsaris** [comment]
The Bluetooth connection isn't that stable in combo with phyton and the underlying Bluetooth libraries. The connection freezes from time to time and then the integration tries to reconnect and takes some time (the time out you experience).

Wasn't able yet to get it fully stable. Current looking into a different solution using a esp32 board

**Comment by fsaris** [comment]
@dasEtwasmitPunkten can you check the latest (0.1.4) release?
