### ISSUE TITLE
Detected blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by tomonwheels** [fsaris/home-assistant-awox#82]
Logger: homeassistant.util.async_
Source: util/async_.py:184 
First occurred: 19:42:18 (1 occurrences) 
Last logged: 19:42:18

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for awox doing blocking calls at custom_components/awox/awox_mesh.py, line 382: devices = await DeviceScanner.async_find_devices(hass=self.hass, scan_timeout=20)

**Comment by tomonwheels** [comment]
I don't know if this is the reason for my all my problems.

After loading Home Assistant the Awox integration works for some minutes. I've connected HomeKit also to HA. When turning off a group of bulbs in HomeKit everything gets very slow. Also after some minutes without using HomeKit. Sometimes it takes a minute or more to turn bulbs on more off.

**Comment by tomonwheels** [comment]
[XK0dI1wz] Requesting status failed - [TimeoutError]
19:45:56 – (WARNUNG) AwoX Mesh Beleuchtung (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal am 19:42:38 aufgetreten und erscheint 3 mal
Timed out connecting to a4:c1:38:72:d8:11 after 15 seconds.
19:45:37 – (FEHLER) AwoX Mesh Beleuchtung (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal am 19:42:35 aufgetreten und erscheint 2 mal
[XK0dI1wz] Command failed, retry 1
19:45:20 – (WARNUNG) AwoX Mesh Beleuchtung (benutzerdefinierte Integration)
[XK0dI1wz][a4:c1:38:6c:a2:07] Disconnect failed: [NotConnectedError]
19:45:20 – (WARNUNG) AwoX Mesh Beleuchtung (benutzerdefinierte Integration)
[XK0dI1wz] Command failed, re-connecting for new attempt - [NotConnectedError] Timed out connecting to a4:c1:38:6c:a2:07 after 15 seconds.
19:45:20 – (FEHLER) AwoX Mesh Beleuchtung (benutzerdefinierte Integration)
[XK0dI1wz][a4:c1:38:6c:a2:07] Command failed, attempt: 0 - [NotificationTimeout] None
19:45:20 – (WARNUNG) AwoX Mesh Beleuchtung (benutzerdefinierte Integration) - Die Nachricht ist zum ersten Mal am 19:45:02 aufgetreten und erscheint 2 mal
Error fetching awox data: No device connected
19:45:06 – (FEHLER) AwoX Mesh Beleuchtung (benutzerdefinierte Integration)
No response received
19:45:02 – (FEHLER) /usr/local/lib/python3.10/site-packages/pygatt/backends/gatttool/gatttool.py
:0:0 Script error.
19:42:45 – (FEHLER) components/system_log/__init__.py
Error fetching awox data: No device connected
19:42:38 – (FEHLER) AwoX Mesh Beleuchtung (benutzerdefinierte Integration)
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for awox doing blocking calls at custom_components/awox/awox_mesh.py, line 382: devices = await DeviceScanner.async_find_devices(hass=self.hass, scan_timeout=20)
19:42:18 – (WARNUNG) util/async_.py

**Comment by pipacsba** [comment]
Since the last update I also have a lot of of this warning:
Logger: homeassistant.util.async_
Source: util/async_.py:184
First occurred: 15:16:22 (90 occurrences)
Last logged: 16:32:01

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for awox doing blocking calls at custom_components/awox/awox_mesh.py, line 382: devices = await DeviceScanner.async_find_devices(hass=self.hass, scan_timeout=20)

**Comment by fsaris** [comment]
Probably related to #95

**Comment by ZTHawk** [comment]
This is still applicable:


Logger: homeassistant.util.async_
Source: util/async_.py:137
First occurred: 16:51:43 (16 occurrences)
Last logged: 17:04:28

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for awox doing blocking calls at custom_components/awox/awox_mesh.py, line 382: devices = await DeviceScanner.async_find_devices(hass=self.hass, scan_timeout=20)

**Comment by fsaris** [comment]
Closed, see #110 for more info.
