### ISSUE TITLE
Inform user that AWOX username must be lowercase

### ISSUE THREAD

**Issue by Marcel1202** [fsaris/home-assistant-awox#83]
Please inform the user in documentation or directly in the integration that your AWOX e-mail must be entered in all lowercase.
Example: Example@gmail.com will successfully log into the phone app but not in the integration
=> example@gmail.com must be entered into the integration to successfully log in.

**Comment by danxdz** [comment]
self._username = username.lower() #Awox Connect API requires lowercase username
