### ISSUE TITLE
smart plug plus stop working

### ISSUE THREAD

**Issue by SergioGomera** [fsaris/home-assistant-awox#89]
After some time my smart plug plus stop working as switch in home assistant, I don’t know in which version start the problems, but now only say don’t available. If you need logs or something tell me. Thx in advance.

_Originally posted by @SergioGomera in https://github.com/fsaris/home-assistant-awox/issues/54#issuecomment-1372886899_

**Comment by fsaris** [comment]
Due to the Bluetooth issues in latest HomeAssistant versions and the fact that the AwoX BLE mesh doesn't respect the BLE standards I start working on a esphome based component to replace this integration https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub

**Comment by SergioGomera** [comment]
> Due to the Bluetooth issues in latest HomeAssistant versions and the fact that the AwoX BLE mesh doesn't respect the BLE standards I start working on a esphome based component to replace this integration https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub

Thx 4 all. I will wait this new integration 😉
