### ISSUE TITLE
It has stopped working.

### ISSUE THREAD

**Issue by Jonesbonew** [fsaris/home-assistant-awox#90]

**Comment by Jonesbonew** [comment]
![Screenshot_20230130_092909_Home Assistant](https://user-images.githubusercontent.com/119678868/215425840-66d78af6-5a5f-48a9-87fe-ad6018130f5e.jpg)

It must have something to do with the Bluetooth integration that i noticed is not running anymore

**Comment by fsaris** [comment]
Due to the Bluetooth issues in latest HomeAssistant versions and the fact that the AwoX BLE mesh doesn't respect the BLE standards I start working on a esphome based component to replace this integration https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub
