### ISSUE TITLE
completely killed my home wifi

### ISSUE THREAD

**Issue by macchrissli** [fsaris/home-assistant-awox#93]
After installing the integration my wifi setup would crawl at super slow speeds. Devices would disconnect regularly. Nothing worked anymore. There is something seriously wrong with the code. 
after uninstalling everything went back to normal. (Of course I only discovered that this integration was the problem after several ours of router restarting and countless other attempts of troubleshooting…)

**Comment by fsaris** [comment]
It's the python Bluetooth integration (see also other issues). Did you check if there was a specific process that had a high CPU usage? 
What hardware are you using?


Side note: I'm currently considering abandoning this integration in favor of the new ESPHome component I'm working on. The Bluetooth integration with HA is to unstable for me. https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub

**Comment by fsaris** [comment]
Please open a new Q&A discussion if you need more support
