### ISSUE TITLE
Problem since Home Assistant Update

### ISSUE THREAD

**Issue by patpac9** [fsaris/home-assistant-awox#95]
Here is the Log output I got:

**1st: ERROR**
Error setting up entry AwoX Smart Connect for awox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/awox/__init__.py", line 38, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**2nd Warning**
[lddAkip4] Command failed, retry 1
[lddAkip4] Command failed, retry 2
[lddAkip4] Command failed, retry 3

**3rd Error **
Error fetching awox data: No device connected

**Comment by OkOtChA666** [comment]
Same

**Comment by patpac9** [comment]
Just realized that this is deprecated.

--> async_setup_platforms

Maybe This can help?
https://community.home-assistant.io/t/async-setup-platforms-deprecated/529444

I went back to 2023.4.6 it works again.

Also had some issues with the new voice assistant functions in the new 2023.5 Version.
It just stops sending entities to Alexa... but that's a whole other topic for other people :D

**Comment by OkOtChA666** [comment]
> Just realized that this is deprecated.
> 
> --> async_setup_platforms
> 
> Maybe This can help? https://community.home-assistant.io/t/async-setup-platforms-deprecated/529444
> 
> I went back to 2023.4.6 it works again.
> 
> Also had some issues with the new voice assistant functions in the new 2023.5 Version. It just stops sending entities to Alexa... but that's a whole other topic for other people :D

I've also downgrade...

**Comment by fsaris** [comment]
Okay some changes are needed indeed https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

I'm open for PR's. Not sure when/if I find time soon to update this

**Comment by fvoigt** [comment]
Hi all,
i replaced the old setup line in the __init___.py with following:
```python
load_ok = all(                                                                                              
        await asyncio.gather(                                                                                   
            *[                                                       
                hass.config_entries.async_forward_entry_setup(entry, component)
                for component in PLATFORMS                                     
            ]                                                                  
        )                                                                      
    )  
``` 
as i'm not a Py dev and thats my first try i would like someone to review and perhaps add that. It was working on my awox Lights.

**Comment by OkOtChA666** [comment]
> Hi all, i replaced the old setup line in the **init**_.py with following:
> 
> ```python
> load_ok = all(                                                                                              
>         await asyncio.gather(                                                                                   
>             *[                                                       
>                 hass.config_entries.async_forward_entry_setup(entry, component)
>                 for component in PLATFORMS                                     
>             ]                                                                  
>         )                                                                      
>     )  
> ```
> 
> as i'm not a Py dev and thats my first try i would like someone to review and perhaps add that. It was working on my awox Lights.

Can you be more specifi... What line did you replaced

**Comment by fvoigt** [comment]
The line which is depricated as fsaris mention in the comment before. https://developers.home-assistant.io/blog/2022/07/08/config_entry_forwards/

**Comment by patpac9** [comment]
Can confirm it works.
Big THANKS to @fvoigt !

I am describing a little bit what has to be done for other Users.

1. Start VSCode Server Add-on or something else with which you can access the folder Config --> Custom integrations.
2. Navigate to Config --> Custom Integrations --> awox.
3. In there you have to open the file: "_init_.py".
4. In the File at line 38 is the deprecated code.
5. Just replace this line with this code below code and it should work.
`load_ok = all(                                                                                              
        await asyncio.gather(                                                                                   
            *[                                                       
                hass.config_entries.async_forward_entry_setup(entry, component)
                for component in PLATFORMS                                     
            ]                                                                  
        )                                                                      
    )  `

**Comment by OkOtChA666** [comment]
Thanks... It works

**Comment by HerraTee** [comment]
Worked for me too. I had to start Awox app from my phone before the lights were re-enabled, but I'm not sure if it was just a coincidence.

**Comment by alfo1133** [comment]
Worked for me too. Big thanks! 
I had to restart the whole Home Assistant to get the changes to be applied (for those that wouldn't know). ;)

**Comment by fsaris** [comment]
Should be resolved with latest version https://github.com/fsaris/home-assistant-awox/releases/tag/0.1.5
