### ISSUE TITLE
wifi/cloud integration?

### ISSUE THREAD

**Issue by dreyks** [fsaris/home-assistant-awox#99]
I know this is a BT integration, but maybe you can point me in a correct direction

I have a BT Eglo lamp and an Eglo smart plug which acts as a wifi <-> mesh bridge. From my phone app, I'm able to operate the lamp even when I'm not within its range - so it works via wifi

unfortunately, my HA server is far enough from the lamp that I can't make a BT-only connection: either the plug doesn't reach the lamp or the server (which is Rpi with built-on bt) can't reach the plug

so he question is is there an Eglo integration that would work similarly to their app, i.e. via wifi?

**Comment by fsaris** [comment]
No sorry, I don't know any integratie that can use the wifi features of Awox.

But maybe you can build a small BT hub based on  https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub that you could position in reach of your plug

**Comment by dreyks** [comment]
I'm trying to build something myself by reading your cloud connection code. is the awox.cloud api you're using a public one? is there any documentation? thx in advance :)

**Comment by fsaris** [comment]
I reversed engineered it by using Wireshark and the app on a old android device ;)

There is no real public API 

Maybe this can help you to get started https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/issues/27#issuecomment-1681117854 I created a little jsfiddle to get the mesh credentials
